FROM eclipse-temurin:24-jdk-alpine

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

COPY src ./src
COPY ./backend/pom.xml ./src

RUN chmod +x mvnw

EXPOSE 8080

CMD [ "./mvnw", "spring-boot:run" ]