FROM eclipse-temurin:24-jdk-alpine

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

COPY src ./src

RUN chmod +x mvnw
RUN sed -i 's/\r$//' mvnw

EXPOSE 8080

CMD [ "./mvnw", "spring-boot:run" ]